/**
 * The machine-readable knowledge feed (/api/ai/knowledge): the hand-written
 * curated list PLUS every published `knowledge_articles` entry the curated list
 * does not already cover.
 *
 * Why a union and not "DB only": 8 of the hand-written articles still live as
 * static pages, not in the DB, so a DB-only feed would silently drop them. The
 * curated wording for an article is kept as-is (DB copies of the same slug are
 * ignored), so nothing that was in the feed changes. Pure (no DB, no Next) so
 * it is unit-testable; the route supplies the data.
 */
import type { KnowledgeArticle } from "./types"

export interface FeedItem {
  title: string
  url: string
  summary: string
  /** Only on entries generated by the Knowledge Base sync: the page they are derived from. */
  source_url?: string
}

const slugOf = (url: string) => url.split("/knowledge/")[1]?.split(/[?#/]/)[0] ?? ""

export function mergeKnowledgeFeed(
  curated: readonly FeedItem[],
  published: readonly KnowledgeArticle[],
  siteUrl: string,
  curatedDate: string,
): { items: FeedItem[]; lastUpdated: string } {
  const covered = new Set(curated.map((c) => slugOf(c.url)))

  const fromDb = published
    .filter((a) => a.isPublished && a.slug && !covered.has(a.slug))
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0) || a.title.localeCompare(b.title))

  const items: FeedItem[] = [
    ...curated,
    ...fromDb.map((a) => ({
      title: a.title,
      url: `${siteUrl}/knowledge/${a.slug}`,
      summary: a.metaDescription,
      ...(a.canonicalUrl ? { source_url: a.canonicalUrl } : {}),
    })),
  ]

  // YYYY-MM-DD strings sort correctly as text. Only dates of what the feed actually lists count.
  const dates = [curatedDate, ...fromDb.map((a) => a.dateModified).filter((d): d is string => /^\d{4}-\d{2}-\d{2}/.test(d ?? ""))]
  const lastUpdated = dates.map((d) => d.slice(0, 10)).sort().at(-1) ?? curatedDate

  return { items, lastUpdated }
}
