/**
 * GTM Container Regenerator
 * GET /api/admin/growth/ads/conversion-actions/gtm-export
 *
 * Returns an updated GTM container JSON with real conversion labels substituted
 * for REPLACE_* placeholders. Ready to import directly into GTM.
 */
import { NextResponse } from "next/server"
import clientPromise from "@/lib/mongodb"
import { AW_CONVERSION_ID, CONVERSION_ACTIONS } from "@/lib/growth-os/conversion-tracking"
import fs from "fs"
import path from "path"

export const dynamic = "force-dynamic"

const COLL       = "ads_conversion_config"
const TEMPLATE   = path.join(process.cwd(), "docs", "gtm-container-import.json")

// Maps canonical action names to their REPLACE_* placeholder in the template JSON.
const LABEL_PLACEHOLDER_MAP: Record<string, string> = {
  "RFQ Submit":          "REPLACE_RFQ_SUBMIT_LABEL",
  "WhatsApp Click":      "REPLACE_WHATSAPP_CLICK_LABEL",
  "Phone Click":         "REPLACE_PHONE_CLICK_LABEL",
  "Dealer Application":  "REPLACE_DEALER_APPLICATION_LABEL",
  "OEM Authorization":   "REPLACE_OEM_AUTH_LABEL",
}

export async function GET() {
  try {
    const db    = (await clientPromise).db()
    const saved = await db.collection(COLL).findOne({ _docId: "conversion-config" }) as Record<string, unknown> | null

    const awId = String(saved?.awConversionId ?? AW_CONVERSION_ID)
    if (awId.includes("REPLACE")) {
      return NextResponse.json(
        { error: "Conversion ID not configured. Enter it in Growth OS → Ads → Conversion Labels first." },
        { status: 400 }
      )
    }

    // Check all labels are configured
    const actions = CONVERSION_ACTIONS.map(a => {
      const entry = (saved?.actions as Array<Record<string, unknown>> ?? []).find(s => s.name === a.name)
      return { name: a.name, label: String(entry?.conversionLabel ?? a.conversionLabel) }
    })
    const unconfigured = actions.filter(a => a.label.includes("REPLACE"))
    if (unconfigured.length > 0) {
      return NextResponse.json(
        { error: `Labels not yet configured: ${unconfigured.map(a => a.name).join(", ")}` },
        { status: 400 }
      )
    }

    // Read template
    let templateStr: string
    try {
      templateStr = fs.readFileSync(TEMPLATE, "utf8")
    } catch {
      return NextResponse.json({ error: "GTM template file not found at docs/gtm-container-import.json" }, { status: 500 })
    }

    // Extract numeric AW ID (AW-123456789 → 123456789)
    const awNumeric = awId.replace(/^AW-/, "")

    // Substitute all placeholders
    let result = templateStr.replace(/REPLACE_AW_NUMERIC_ID/g, awNumeric)
    for (const { name, label } of actions) {
      const placeholder = LABEL_PLACEHOLDER_MAP[name]
      if (placeholder) result = result.replace(new RegExp(placeholder, "g"), label)
    }

    // Update container version name with today's date
    const today = new Date().toISOString().slice(0, 10)
    const parsed = JSON.parse(result)
    if (parsed.containerVersion) {
      parsed.containerVersion.name        = `100X Circle — Conversions (${today})`
      parsed.containerVersion.description = `Generated by Growth OS on ${today}. AW-ID: ${awId}.`
    }

    return new NextResponse(JSON.stringify(parsed, null, 2), {
      status: 200,
      headers: {
        "Content-Type":        "application/json",
        "Content-Disposition": `attachment; filename="gtm-100xcircle-${today}.json"`,
      },
    })
  } catch (err) {
    console.error("[gtm-export]", String(err))
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
