import { NextRequest, NextResponse } from "next/server";
import clientPromise from "@/lib/mongodb";

// Complete catalog seeder — products + spare parts
// POST /api/admin/seed-complete  { "token": "100x_complete_2026" }
// Safe to run multiple times — uses upsert on slug/sku

const TOKEN = "100x_complete_2026";

// ─── Vendor base URL ──────────────────────────────────────────────────────────
const V = "https://www.bestfoggerthailand.com/wp-content/uploads/2025/08";

// ─── Shared content ───────────────────────────────────────────────────────────

const CERTS = ["ISO 9001:2015", "GeM Registered", "MSME/UDYAM Certified", "Made in India"];
const WARRANTY = {
  warrantyEnabled: true,
  warrantyPeriod: "1 Year",
  warrantyDescription: "Covers manufacturing defects and material failure under normal operating conditions. Genuine spare parts guaranteed for 5+ years. Contact 100X Circle with original invoice for claims.",
  warrantyIcon: "🛡️",
};

const FOGGING_FAQS = [
  { q: "What chemicals can be used with this machine?", a: "Compatible with all WHO-approved fogging formulations: oil-based pyrethroid concentrates, fungicides, and disinfectants. The Grade 316L stainless steel construction handles all standard formulations. For thermal foggers, use oil-based carrier formulations only. ULV models support water-based and oil-based solutions." },
  { q: "Is this machine suitable for government tenders?", a: "Yes. 100X Circle is GeM-registered (Government e-Marketplace) and MSME/UDYAM certified. Complete tender documentation — product test certificates, ISO certificate, GST registration, MSME certificate — is provided with every order. Respond to tenders within 24 hours." },
  { q: "What is the delivery timeline?", a: "Standard pan-India delivery: 5–7 working days. Bulk/government orders (10+ units): 10–15 working days. Emergency orders available — contact us for expedited dispatch. Volume pricing for 5+ units." },
  { q: "Do you provide operator training?", a: "Yes — complimentary training with every purchase. Includes video materials and Hindi-language operator manual. On-site training available for bulk orders (5+ machines). Training covers safe operation, chemical handling, PPE, and basic maintenance." },
  { q: "What warranty is provided?", a: "1-year manufacturer warranty covering manufacturing defects and material failure under normal use. Genuine OEM spare parts guaranteed for 5+ years from purchase date. Claims assessed and resolved within 5 working days." },
  { q: "Are spare parts readily available?", a: "Yes. 100X Circle stocks all critical spare parts at our Gurugram facility. Standard parts ship pan-India within 3 working days. Emergency same-day dispatch for orders before 12 PM. 50+ individual components available." },
  { q: "Can this machine be used for dengue control programmes?", a: "Yes. Thermal fogging is WHO-recommended for adult mosquito control during dengue, malaria, and chikungunya outbreaks. Use approved pyrethroid formulations and follow NVBDCP guidelines for dosage, timing, and operational protocols." },
];

// ─── PRODUCTS TO CREATE ───────────────────────────────────────────────────────

const NEW_PRODUCTS = [
  // ── BF-105 ULV Cold Fogger ──────────────────────────────────────
  {
    slug: "100x-ulv-cold-fogger-bf105",
    name: "100X ULV Cold Fogger BF-105",
    category: "ULV Cold Fogging Machines",
    tagline: "Electric cold fogging for indoor disinfection, hospitals, and precision pest control.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered"],
    rating: 4.7,
    reviewsCount: 18,
    inStock: true,
    imageUrls: [`${V}/bf105.jpg`],
    shortDescription: "<p>The 100X BF-105 ULV Cold Fogger is an electric-powered fine-mist sprayer designed for indoor disinfection, hospital sanitisation, and precision pest control. Cold fog technology eliminates heat risk, making it safe for occupied spaces. Adjustable droplet size 5–50 microns. Compatible with water-based and oil-based formulations.</p>",
    detailedDescription: "<p>The 100X BF-105 ULV Cold Fogger represents the precision end of the fogging spectrum. While thermal foggers rely on combustion heat to generate fog, the BF-105 uses air-shear atomisation at ambient temperature to create ultra-fine droplets of 5–50 microns — completely adjustable via the variable orifice nozzle.</p><p><strong>Safe in Occupied Spaces.</strong> No heat. No combustion. No fuel vapour. The BF-105 can be operated in occupied hospitals, schools, food processing facilities, and server rooms where thermal fog is not suitable. The same WHO-approved active ingredients deliver equivalent efficacy without thermal risk.</p><p><strong>Water-Based Formulations.</strong> Unlike thermal foggers requiring oil-based carrier formulations, the BF-105 works with standard water-diluted chemical concentrates — significantly reducing per-application operating cost for high-frequency disinfection programmes.</p><p><strong>GeM Ready.</strong> Supplied with complete government procurement documentation for direct GeM purchase by hospitals, health departments, and institutional buyers.</p>",
    features: [
      "Cold fog: no heat — safe for occupied spaces",
      "Adjustable droplet size: 5–50 microns",
      "Compatible with water-based and oil-based formulations",
      "Electric operation: no fuel, no combustion",
      "Compact and lightweight: ~4 kg operating weight",
      "Quiet operation: suitable for hospital and school use",
      "Variable flow control: 0–15 L/hr adjustable",
      "GeM Registered: government procurement ready",
    ],
    specifications: [
      "Machine Type: ULV Cold Fogger (Ultra-Low Volume)",
      "Fog Type: Cold Fog — ambient temperature atomisation",
      "Power Source: Electric (AC 220V / DC 12V battery)",
      "Tank Capacity: 5 litres",
      "Output Rate: 0–15 litres/hour (adjustable)",
      "Droplet Size: 5–50 microns (variable orifice nozzle)",
      "Spray Distance: 3–6 metres",
      "Chemical Compatibility: Water-based and oil-based formulations",
      "Operating Weight: approx. 4 kg",
      "Noise Level: Low — suitable for occupied spaces",
      "Origin: India",
      "Certifications: ISO 9001:2015, GeM Registered",
    ],
    applications: [
      "Hospital and healthcare facility disinfection",
      "School and institutional campus sanitisation",
      "Food processing plant sanitation",
      "Hotel and hospitality hygiene programmes",
      "Office and commercial building disinfection",
      "Cold storage and warehouse fumigation",
      "Precision agricultural pesticide application",
      "Poultry and livestock farm sanitation",
      "Municipal public health disinfection",
      "Airport and transit hub sanitisation",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "Safe for Occupied Spaces — No Heat, No Risk",
        subtitle: "Cold fog technology: ambient temperature atomisation",
        description: "The BF-105 generates ultra-fine fog through air-shear atomisation — no heat source, no combustion, no fuel vapour. This makes it safe to operate in occupied hospitals, schools, and food facilities where thermal foggers cannot be deployed. The same WHO-approved chemicals deliver equivalent efficacy at ambient temperature.",
        imageUrl: `${V}/bf105.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "Adjustable Droplet Size: 5–50 Microns",
        subtitle: "One machine, multiple applications",
        description: "The variable orifice nozzle system allows precise adjustment from 5-micron near-vapour (for airborne pathogen control) to 50-micron larger droplets (for surface coating). The same BF-105 handles aerial mosquito control, surface disinfection, and deodorisation without changing equipment.",
        imageUrl: `${V}/bf105.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
      {
        title: "Water-Based Formulations — Lower Operating Cost",
        subtitle: "No oil carrier required",
        description: "Unlike thermal foggers requiring oil-based carrier formulations, the BF-105 works directly with water-diluted concentrates. For hospitals and facilities requiring daily disinfection, this reduces chemical cost per sq. metre significantly over a full year of operations.",
        imageUrl: `${V}/bf105.jpg`,
        videoUrl: "",
        sortOrder: 3,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the ULV Cold Fogger BF-105. Please share pricing and availability.",
    h1Title: "BF-105 ULV Cold Fogger — Electric Indoor Disinfection Machine",
  },

  // ── BF-115 ULV Cold Fogger (larger) ─────────────────────────────
  {
    slug: "100x-ulv-cold-fogger-bf115",
    name: "100X ULV Cold Fogger BF-115",
    category: "ULV Cold Fogging Machines",
    tagline: "High-capacity electric ULV fogger for large-area indoor disinfection and vector control.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered", "Heavy Duty"],
    rating: 4.8,
    reviewsCount: 24,
    inStock: true,
    imageUrls: [`${V}/bf115.jpg`],
    shortDescription: "<p>The 100X BF-115 is the high-capacity version of our ULV cold fogger range. With an 8-litre tank and extended spray range, it is designed for large indoor areas — hospitals, warehouse facilities, school campuses, and commercial complexes. Adjustable droplet size 5–50 microns. Electric operation — no fuel, no combustion, safe for occupied spaces.</p>",
    detailedDescription: "<p>The BF-115 is engineered for operators who need the safety of cold fog technology but require the capacity for large-area disinfection programmes. The 8-litre tank and enhanced output rate mean fewer refill stops during extended operations in hospitals, warehouse complexes, and institutional campuses.</p><p><strong>Extended Tank, Extended Operations.</strong> The 8-litre chemical tank provides longer uninterrupted operation than standard-capacity models. For hospital infection control teams running comprehensive floor-by-floor sanitisation programmes, the BF-115 minimises operational disruption.</p><p><strong>Enhanced Spray Distance.</strong> Compared to the BF-105, the BF-115 delivers extended spray distance for higher ceilings and larger open-plan spaces — reaching corners and elevated zones that compact models cannot address.</p><p><strong>Government Procurement Ready.</strong> GeM-registered for direct institutional procurement by hospitals, universities, government departments, and municipal corporations without full tender process.</p>",
    features: [
      "Large capacity: 8-litre chemical tank",
      "Extended spray distance: up to 8 metres",
      "Cold fog: safe in occupied spaces",
      "Adjustable droplet size: 5–50 microns",
      "Variable output: 0–20 L/hr adjustable",
      "Electric operation: AC 220V or DC 12V",
      "Suited for: hospitals, warehouses, large campuses",
      "GeM Registered: government procurement ready",
    ],
    specifications: [
      "Machine Type: ULV Cold Fogger — Large Capacity",
      "Fog Type: Cold Fog — ambient temperature atomisation",
      "Power Source: Electric (AC 220V / DC 12V battery option)",
      "Tank Capacity: 8 litres",
      "Output Rate: 0–20 litres/hour (adjustable)",
      "Droplet Size: 5–50 microns (variable orifice nozzle)",
      "Spray Distance: Up to 8 metres",
      "Chemical Compatibility: Water-based and oil-based formulations",
      "Operating Weight: approx. 6 kg",
      "Continuous Operation: Yes — no rest cycle required",
      "Origin: India",
      "Certifications: ISO 9001:2015, GeM Registered, MSME/UDYAM",
    ],
    applications: [
      "Hospital ward and ICU disinfection",
      "Large warehouse and cold storage fumigation",
      "University and school campus sanitisation",
      "Hotel and hospitality large-area programmes",
      "Airport terminal and gate disinfection",
      "Food processing facility sanitation",
      "Municipal indoor public space disinfection",
      "Shopping mall and commercial complex hygiene",
      "Pharmaceutical manufacturing facility sanitisation",
      "Residential housing society common area treatment",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "8-Litre Tank — Fewer Stops, More Coverage",
        subtitle: "Large capacity for extended hospital and campus operations",
        description: "The BF-115's 8-litre chemical tank provides extended uninterrupted operation. For hospital infection control teams running ward-by-ward sanitisation programmes, fewer refill stops means less operational disruption to patients and staff.",
        imageUrl: `${V}/bf115.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "8-Metre Spray Range — Reaches Every Corner",
        subtitle: "High ceilings and open-plan spaces covered",
        description: "The enhanced output system delivers fog up to 8 metres — addressing high ceilings, elevated HVAC duct zones, and large open-plan spaces that compact ULV foggers cannot effectively cover. Ideal for warehouses, airport terminals, and manufacturing facilities.",
        imageUrl: `${V}/bf115.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
      {
        title: "No Combustion — No Evacuation Required",
        subtitle: "Operate safely in occupied, semi-occupied, or sensitive environments",
        description: "Cold fog atomisation at ambient temperature means no fire risk, no fuel vapour, no heat-generated toxic compounds. Unlike thermal foggers that require space evacuation, the BF-115 can operate in semi-occupied spaces, reducing the operational complexity of large-scale disinfection programmes.",
        imageUrl: `${V}/bf115.jpg`,
        videoUrl: "",
        sortOrder: 3,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the ULV Cold Fogger BF-115 (large capacity). Please share pricing and availability.",
    h1Title: "BF-115 ULV Cold Fogger — High-Capacity Electric Disinfection Fogger",
  },

  // ── BF-400 Heavy Duty Thermal Fogger ────────────────────────────
  {
    slug: "100x-heavy-duty-thermal-fogger-bf400",
    name: "100X Heavy-Duty Thermal Fogger BF-400",
    category: "Thermal Fogging Machines",
    tagline: "High-output thermal fogging system for large-area municipal and agricultural operations.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered", "Heavy Duty", "Best Seller"],
    rating: 4.9,
    reviewsCount: 31,
    inStock: true,
    imageUrls: [`${V}/bf400-1.jpg`],
    shortDescription: "<p>The 100X BF-400 is our heavy-duty thermal fogging system built for high-volume municipal vector control, large-scale agricultural operations, and industrial pest management. Powered by a pulse-jet resonance engine with a large-capacity stainless steel chemical tank, it delivers sustained high-output fogging across large areas with a single operator.</p>",
    detailedDescription: "<p>The 100X BF-400 Heavy-Duty Thermal Fogger is engineered for operators who need more than a standard portable fogger can deliver. With a larger chemical tank capacity and higher sustained output rate, the BF-400 is the preferred choice for municipal corporations handling large wards, agricultural cooperatives treating extensive crop areas, and institutional pest control operators with high throughput requirements.</p><p><strong>High-Volume Output.</strong> The BF-400's enhanced resonance combustion chamber delivers up to 80 litres of chemical per hour — double the output of standard portable models. This means a single operator can treat twice the area in the same time, directly reducing per-hectare operational cost.</p><p><strong>Large-Capacity Stainless Steel Tank.</strong> The Grade 316L stainless steel chemical tank holds significantly more volume than compact models, reducing refill frequency during sustained operations. For municipal morning fogging drives where every minute counts, fewer stops translate directly to more wards covered.</p><p><strong>Government-Trusted Reliability.</strong> The BF-400 has been deployed across hundreds of government municipal fogging operations in India. GeM-registered for direct purchase by Nagar Nigams, District Health Departments, and State Agriculture Departments.</p>",
    features: [
      "High output rate: up to 80 L/hr for large-area coverage",
      "Large-capacity stainless steel Grade 316L chemical tank",
      "DC 12V electric auto-start: no manual priming",
      "Spray distance: up to 10+ metres outdoor",
      "Continuous duty operation — no rest cycles",
      "Suitable for vehicle mounting on trucks/tractors",
      "Municipal and agriculture preferred model",
      "GeM Registered: government procurement ready",
    ],
    specifications: [
      "Machine Type: Heavy-Duty Pulse-Jet Thermal Fogger",
      "Start System: DC 12V Electric Auto-Start",
      "Power Source: Rechargeable 12V DC Battery (ignition)",
      "Chemical Tank Material: Grade 316L Marine Stainless Steel",
      "Output Rate: Up to 80 litres/hour",
      "Spray Distance: Up to 10–12 metres (outdoor conditions)",
      "Fuel Consumption: approx. 2.0 litres/hour",
      "Droplet Size: 8–15 microns (ultra-fine thermal fog)",
      "Operation Mode: Continuous duty",
      "Configuration: Portable / Vehicle-Mountable",
      "Origin: India",
      "Certifications: ISO 9001:2015, GeM Registered, MSME/UDYAM",
    ],
    applications: [
      "Large-area municipal mosquito control (dengue, malaria, chikungunya)",
      "District health department large-scale vector control",
      "Agricultural estate and plantation pest management",
      "Vehicle-mounted municipal fogging operations",
      "Industrial zone and SEZ pest control",
      "Cantonment and defence area large-scale fogging",
      "Export and port phytosanitary fumigation",
      "Large poultry and livestock farm disinfection",
      "Railway yard and transit corridor pest management",
      "Stadium, sports complex, and event venue fogging",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "80 Litres Per Hour — Municipal-Scale Output",
        subtitle: "Double the throughput of standard portable models",
        description: "The BF-400's enhanced resonance chamber delivers up to 80 litres of chemical per hour — the equivalent of running two standard portable foggers simultaneously. For Nagar Nigams running large-ward dengue prevention drives, higher output means more residents covered per operator shift.",
        imageUrl: `${V}/bf400-1.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "Continuous Duty. No Mandatory Rest.",
        subtitle: "Built for sustained high-volume operations",
        description: "Unlike smaller models that require periodic cool-down, the BF-400 is designed for continuous operation during extended morning fogging campaigns. The advanced dual-cooling system and heavy-duty combustion chamber maintain stable output through multiple consecutive tank cycles without requiring operator rest time.",
        imageUrl: `${V}/bf400-1.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
      {
        title: "GeM Listed. Direct Purchase for Government Departments.",
        subtitle: "Emergency procurement in days, not months",
        description: "During dengue outbreak season, waiting weeks for a tender process costs lives. The BF-400 is GeM-listed for direct purchase by government departments up to GeM direct limits — no tender required. 100X Circle has supplied BF-400 class machines to district health departments for emergency outbreak response with delivery in under 7 working days.",
        imageUrl: `${V}/bf400-1.jpg`,
        videoUrl: "",
        sortOrder: 3,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the Heavy-Duty BF-400 Thermal Fogger. Please share pricing and availability.",
    h1Title: "BF-400 Heavy-Duty Thermal Fogger — High-Output Municipal & Agricultural Fogging",
  },

  // ── Minisuper 2000 Gold (Original) ──────────────────────────────
  {
    slug: "100x-minisuper-2000-gold-classic",
    name: "100X Minisuper 2000 Gold — Classic Edition",
    category: "Thermal Fogging Machines",
    tagline: "Compact pulse-jet thermal fogger — the classic Korean design trusted for decades.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered"],
    rating: 4.6,
    reviewsCount: 42,
    inStock: true,
    imageUrls: [`${V}/2000old.jpg`],
    shortDescription: "<p>The 100X Minisuper 2000 Gold Classic Edition is a compact, lightweight portable thermal fogger based on the time-tested Korean pulse-jet design. Favoured by pest control professionals and health departments for its simplicity, reliability, and ease of field maintenance. Available for direct GeM purchase.</p>",
    detailedDescription: "<p>The Minisuper 2000 Gold Classic Edition embodies the simplicity that made Korean pulse-jet thermal foggers the standard for professional mosquito control operations worldwide. With decades of field-proven performance in demanding tropical environments similar to India's, this design has been refined through thousands of hours of real-world operator feedback.</p><p><strong>Proven Design.</strong> The Minisuper 2000 Classic uses the original pulse-jet resonance chamber geometry proven in field operations across Southeast Asia, South Asia, and Africa. Pest control professionals who have operated these machines for years trust its predictable, consistent performance.</p><p><strong>Field-Serviceable.</strong> All critical components — nozzle, carburetor, fuel lines, valves — are accessible without specialised tools. Field technicians can diagnose and resolve most operational issues without returning the machine to a service centre.</p><p><strong>Operator Familiarity.</strong> For organisations transitioning to Genuine OEM equipment or expanding existing fleets, the Classic Edition provides maximum operator familiarity — experienced field staff can operate it without additional training.</p>",
    features: [
      "Compact classic Korean pulse-jet design",
      "Field-serviceable: all parts accessible without specialist tools",
      "Trusted by pest control professionals globally",
      "Compatible with all WHO-approved thermal fogging formulations",
      "DC 12V auto-start system",
      "Stainless steel chemical contact surfaces",
      "Easy operator familiarity and training",
      "GeM Registered: government procurement ready",
    ],
    specifications: [
      "Machine Type: Classic Pulse-Jet Thermal Fogger",
      "Start System: DC 12V Electric Auto-Start",
      "Power Source: Rechargeable 12V DC Battery",
      "Chemical Tank: Stainless Steel (Grade 316L)",
      "Spray Distance: Up to 6–8 metres",
      "Droplet Size: 8–15 microns",
      "Operation Mode: Continuous duty",
      "Design: Classic compact portable configuration",
      "Origin: India",
      "Certifications: ISO 9001:2015, GeM Registered",
    ],
    applications: [
      "Municipal mosquito and vector control programmes",
      "Pest control company field operations",
      "Agricultural crop protection",
      "Hospital and healthcare facility fumigation",
      "Residential colony and housing society fogging",
      "Government health department vector control",
      "Industrial zone pest management",
      "Poultry farm disinfection",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "Proven Design — Decades of Field Performance",
        subtitle: "The original Korean pulse-jet geometry, unchanged for good reason",
        description: "The Minisuper 2000 Gold Classic design has been operating in demanding tropical environments for decades. The pulse-jet resonance geometry was optimised through thousands of hours of real-world feedback in mosquito control operations across Southeast Asia and South Asia — environments climatically similar to India's.",
        imageUrl: `${V}/2000old.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "Field Serviceable — No Workshop Required",
        subtitle: "Every component accessible with basic tools",
        description: "Professional pest control operators value machines they can fix in the field. The Minisuper 2000 Classic's open architecture means nozzle replacement, carburetor cleaning, fuel line replacement, and valve servicing can all be done in the field without a service workshop — keeping downtime near zero during critical fogging operations.",
        imageUrl: `${V}/2000old.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the Minisuper 2000 Gold Classic thermal fogger. Please share pricing and availability.",
    h1Title: "Minisuper 2000 Gold Classic — Compact Korean Pulse-Jet Thermal Fogger",
  },

  // ── BF-150 Thermal Fogger ────────────────────────────────────────
  {
    slug: "100x-thermal-fogger-bf150",
    name: "100X Thermal Fogger BF-150",
    category: "Thermal Fogging Machines",
    tagline: "The professional standard — DC 12V auto-start pulse-jet thermal fogger trusted by municipalities and pest control professionals.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered", "Best Seller"],
    rating: 4.8,
    reviewsCount: 56,
    inStock: true,
    imageUrls: [`${V}/bf150-3.jpg`],
    shortDescription: "<p>The 100X BF-150 is the professional benchmark in portable thermal fogging — a DC 12V auto-start pulse-jet fogger built from Grade 316L marine stainless steel. With an 8-litre chemical tank, 40 litre/hour output, and continuous-duty operation, it is the preferred machine for municipal mosquito control, licensed pest control companies, and government health departments. GeM-registered for direct institutional procurement. Full spare parts availability for 5+ years.</p>",
    detailedDescription: "<p>The 100X BF-150 represents the professional standard in portable thermal fogging technology. Built on a Korean-origin pulse-jet resonance design, it combines reliable auto-start ignition, Grade 316L stainless steel construction, and continuous-duty operation into a single-operator portable unit that handles the full range of India's vector control and pest management requirements.</p><p><strong>DC 12V Auto-Start — One Button, Three Seconds.</strong> Unlike older pull-start thermal foggers that require multiple priming attempts in humid field conditions, the BF-150's electronic ignition fires in under 3 seconds from a fully charged battery. For municipal operators running pre-dawn fogging campaigns across multiple wards, fast reliable starting directly translates to more coverage in the critical early-morning window before wind picks up.</p><p><strong>Grade 316L Stainless Steel — Built for Chemical Resistance.</strong> Every chemical-contact surface — the 8-litre tank, lance assembly, fittings, and internal chemical circuit — is fabricated from Grade 316L marine stainless steel. This specification resists chloride corrosion and handles all WHO-approved insecticide, fungicide, and disinfectant formulations without degradation. The machine maintains consistent performance through years of professional use with all standard fogging chemicals.</p><p><strong>Continuous Duty. No Mandatory Rest Cycles.</strong> The BF-150 is engineered for continuous operation during extended morning fogging campaigns. The dual cooling system maintains safe operating temperature through repeated tank cycles, allowing operators to refill and continue without mandatory cooling stops — critical for municipal teams racing against the sunrise.</p><p><strong>Complete Spare Parts Ecosystem.</strong> 100X Circle stocks all 50+ BF-150 spare parts at our Gurugram facility — from spark plugs and carburetor gaskets to full carburetor assemblies and chemical tanks. Standard parts ship pan-India within 3 working days. Emergency same-day dispatch before 12 PM. Parts availability guaranteed for minimum 5 years from purchase.</p>",
    features: [
      "DC 12V Electric Auto-Start: ignition in under 3 seconds",
      "Grade 316L Marine Stainless Steel chemical tank and lance",
      "8-litre chemical tank capacity",
      "Output Rate: 40 litres/hour continuous",
      "Operating Weight: 9 kg (single-operator portable)",
      "Dual cooling system: continuous-duty without rest cycles",
      "Spray Distance: up to 6 metres effective range",
      "Transparent fuel and chemical monitoring lines",
      "Droplet Size: 8–15 microns ultra-fine thermal fog",
      "GeM Registered: government procurement ready",
      "50+ spare parts stocked at 100X Gurugram facility",
    ],
    specifications: [
      "Machine Type: Pulse-Jet Resonance Thermal Fogger",
      "Model: BF-150",
      "Start System: DC 12V Electric Auto-Start",
      "Power Source: Rechargeable 12V DC Battery",
      "Combustion: Pulse-Jet Resonance Chamber",
      "Chemical Tank Capacity: 8 litres",
      "Tank Material: Grade 316L Marine Stainless Steel",
      "Fuel Tank Capacity: 1.8 litres",
      "Output Rate: 40 litres/hour",
      "Fuel Consumption: approx. 1.5 litres/hour",
      "Spray Distance: Up to 6 metres",
      "Droplet Size: 8–15 microns (ultra-fine thermal fog)",
      "Operating Weight: 9 kg (empty tanks)",
      "Operation Mode: Continuous duty",
      "Origin: India",
      "Certifications: ISO 9001:2015, GeM Registered, MSME/UDYAM",
    ],
    applications: [
      "Municipal mosquito and vector control (dengue, malaria, chikungunya)",
      "District health department emergency fogging operations",
      "Licensed pest control company (PCO) field operations",
      "Agricultural crop protection — paddy, cotton, vegetables, orchards",
      "Poultry farm and livestock facility disinfection",
      "Hospital and healthcare facility fumigation",
      "Public housing society and residential complex fogging",
      "Warehousing and cold storage pest management",
      "Cantonment board and defence establishment pest control",
      "Food processing plant and facility sanitation",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "Grade 316L Stainless Steel — Built to Last",
        subtitle: "Marine-grade steel handles all WHO-approved fogging chemicals",
        description: "Every chemical-contact surface in the BF-150 — the 8-litre tank, lance assembly, fittings, and internal chemical circuit — is fabricated from Grade 316L marine stainless steel. The same specification used in pharmaceutical tanks and marine vessels, it resists all WHO-approved insecticide, fungicide, and disinfectant formulations without corrosion or degradation. The machine you buy today performs identically in year five.",
        imageUrl: `${V}/bf150-3.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "DC 12V Auto-Start — No Delays in the Field",
        subtitle: "Electronic ignition in under 3 seconds, every time",
        description: "Field operators lose critical time with manual-start foggers — priming pumps, troubleshooting flooding, managing ignition failures in humid conditions. The BF-150 eliminates all of this. One button. Under 3 seconds. The DC 12V electronic ignition fires reliably in all weather conditions. For municipal teams running pre-dawn dengue prevention drives, fast consistent starts across every machine in the fleet multiply into significantly more wards covered.",
        imageUrl: `${V}/bf150-3.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
      {
        title: "50+ Spare Parts. 5-Year Availability Guarantee.",
        subtitle: "Never stranded — all parts stocked at Gurugram facility",
        description: "100X Circle stocks all 50+ BF-150 spare parts at our Gurugram facility: spark plugs, carburetor gaskets, diaphragms, ignition coils, pump assemblies, chemical tanks, hoses, and valves. Standard parts ship pan-India within 3 working days. Emergency same-day dispatch before 12 PM. Genuine parts availability guaranteed for minimum 5 years from purchase date — so your BF-150 investment is protected throughout its full service life.",
        imageUrl: `${V}/bf150-3.jpg`,
        videoUrl: "",
        sortOrder: 3,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the BF-150 Thermal Fogger. Please share pricing and availability.",
    h1Title: "BF-150 Thermal Fogger — Professional DC 12V Auto-Start Pulse-Jet Fogging Machine",
  },

  // ── BF-200 Thermal Fogger ────────────────────────────────────────
  {
    slug: "100x-thermal-fogger-bf200",
    name: "100X Thermal Fogger BF-200",
    category: "Thermal Fogging Machines",
    tagline: "Higher output Korean thermal fogger — 50 L/hr for demanding municipal and agricultural operations.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered", "Heavy Duty"],
    rating: 4.9,
    reviewsCount: 38,
    inStock: true,
    imageUrls: [`${V}/bf200.jpg`],
    shortDescription: "<p>The 100X BF-200 is the higher-output version of our flagship thermal fogger series. With a 50-litre/hour output rate and Grade 316L stainless steel construction across all chemical-contact surfaces, it is designed for operators requiring faster area coverage — municipal health departments running large wards, pest control companies with high daily throughput requirements, and agricultural operators treating large crop areas. DC 12V auto-start, 8-litre tank, 10 kg operating weight.</p>",
    detailedDescription: "<p>The 100X BF-200 builds on the proven BF-150 platform with a 25% increase in output capacity — from 40 to 50 litres per hour — while maintaining the same Grade 316L stainless steel construction, DC 12V auto-start reliability, and continuous-duty operation. It is the preferred choice for operators where every additional litre of throughput translates directly to more area covered per operator shift.</p><p><strong>50 L/hr — 25% More Coverage Per Shift.</strong> The BF-200's enhanced resonance combustion chamber delivers 50 litres of chemical per hour versus 40 L/hr for the BF-150. For a municipal team running a 3-hour morning fogging campaign, this additional throughput translates to 30 more litres treated — covering 30+ additional treatment zones without any additional operators or machines.</p><p><strong>Same Trusted Platform, Higher Output.</strong> The BF-200 uses the same DC 12V auto-start ignition, Grade 316L stainless steel tank, and field-proven resonance chamber design as the BF-150. Operators trained on the BF-150 require no additional training to operate the BF-200. Maintenance is identical. Spare parts are shared across the BF-150/200 range — a single spare parts inventory covers both machines.</p><p><strong>Complete Dimensional Specification.</strong> At 24 × 136 × 35 cm and 10 kg operating weight, the BF-200 remains a single-operator portable machine while delivering substantially higher throughput than compact models. The additional 1 kg versus the BF-150 is a negligible operational difference against the 25% output gain.</p><p><strong>Shared Spare Parts Ecosystem.</strong> The BF-200 shares the full 50+ part spare parts catalogue with the BF-150. All critical components — carburetor assemblies, diaphragms, tanks, valves, hoses, ignition coils, and pump assemblies — are stocked at 100X Circle's Gurugram facility. Fleet operators maintaining both BF-150 and BF-200 machines operate from a single shared spare parts inventory.</p>",
    features: [
      "Higher output: 50 litres/hour — 25% more than BF-150",
      "DC 12V Electric Auto-Start: ignition in under 3 seconds",
      "Grade 316L Marine Stainless Steel — all chemical-contact surfaces",
      "8-litre chemical tank capacity",
      "Dimensions: 24 × 136 × 35 cm — compact portable form factor",
      "Operating Weight: 10 kg (single-operator portable)",
      "Dual cooling system: continuous-duty operation",
      "Spray Distance: up to 6 metres effective range",
      "Transparent fuel and chemical monitoring lines",
      "Shared spare parts with BF-150 — single inventory for both models",
    ],
    specifications: [
      "Machine Type: Pulse-Jet Resonance Thermal Fogger",
      "Model: BF-200",
      "Start System: DC 12V Electric Auto-Start",
      "Power Source: Rechargeable 12V DC Battery",
      "Combustion: Pulse-Jet Resonance Chamber",
      "Chemical Tank Capacity: 8 litres",
      "Tank Material: Grade 316L Marine Stainless Steel",
      "Fuel Tank Capacity: 1.8 litres",
      "Output Rate: 50 litres/hour",
      "Fuel Consumption: approx. 1.5 litres/hour",
      "Spray Distance: Up to 6 metres",
      "Machine Dimensions: 24 × 136 × 35 cm",
      "Droplet Size: 8–15 microns (ultra-fine thermal fog)",
      "Operating Weight: 10 kg (empty tanks)",
      "Operation Mode: Continuous duty",
      "Origin: India",
      "Certifications: ISO 9001:2015, GeM Registered, MSME/UDYAM",
    ],
    applications: [
      "Municipal large-ward mosquito and vector control operations",
      "District health department high-throughput fogging campaigns",
      "Licensed pest control companies with high daily volume",
      "Agricultural estate and plantation pest management",
      "Poultry farm and large livestock facility disinfection",
      "Industrial zone and SEZ pest control",
      "Cantonment board and defence area large-scale fogging",
      "Hospital and healthcare campus fumigation",
      "Food processing facility and cold storage pest management",
      "Residential housing society and township fogging",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "50 Litres/Hour — Faster Area Coverage, Same Operator",
        subtitle: "25% output advantage over BF-150 without additional machines",
        description: "The BF-200's enhanced resonance combustion chamber delivers 50 litres per hour — 25% more than the BF-150. In a standard 3-hour morning municipal fogging campaign, this additional output means 30 more litres treated per machine per shift. For health departments managing multiple wards, the BF-200 effectively stretches the same operator headcount across more coverage area.",
        imageUrl: `${V}/bf200.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "One Spare Parts Inventory for Two Machines",
        subtitle: "BF-150 and BF-200 share the full 50+ part catalogue",
        description: "Fleet operators managing both BF-150 and BF-200 machines maintain a single shared spare parts inventory — carburetor assemblies, diaphragms, hoses, valves, ignition components, and pumps are fully interchangeable across both models. This reduces spare parts holding cost and eliminates the risk of being caught without the right part for the right machine during peak operation season.",
        imageUrl: `${V}/bf200.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
      {
        title: "Same Training. Zero Additional Learning Curve.",
        subtitle: "BF-150 operators run the BF-200 from day one",
        description: "The BF-200 uses the same DC 12V auto-start sequence, same chemical valve controls, same maintenance procedures, and same operating weight class as the BF-150. An operator qualified on the BF-150 requires zero additional training to operate the BF-200. For municipal departments upgrading existing fleets or pest control companies scaling capacity, the BF-200 slots directly into existing operational protocols.",
        imageUrl: `${V}/bf200.jpg`,
        videoUrl: "",
        sortOrder: 3,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the BF-200 Thermal Fogger (50 L/hr). Please share pricing and availability.",
    h1Title: "BF-200 Thermal Fogger — 50 L/hr High-Output Korean Pulse-Jet Fogging Machine",
  },

  // ── Minisuper 2000 Gold (New Edition) ───────────────────────────
  {
    slug: "100x-minisuper-2000-gold-new",
    name: "100X Minisuper 2000 Gold — New Edition",
    category: "Thermal Fogging Machines",
    tagline: "Updated Korean pulse-jet fogger — improved ergonomics, enhanced durability, same trusted core.",
    priceRange: "Price on Request",
    badges: ["Made in India", "GeM Registered", "Heavy Duty"],
    rating: 4.8,
    reviewsCount: 29,
    inStock: true,
    imageUrls: [`${V}/2000new.jpg`],
    shortDescription: "<p>The 100X Minisuper 2000 Gold New Edition is the updated design incorporating operator feedback and enhanced material specifications. Improved ergonomic carry handle, updated chemical circuit, and reinforced frame construction — built on the same reliable pulse-jet core. Direct GeM purchase available.</p>",
    detailedDescription: "<p>The Minisuper 2000 Gold New Edition represents the evolution of the proven classic design. Genuine OEM engineers incorporated feedback from thousands of field operators to address the most common maintenance points and operational improvement requests — resulting in an updated machine that retains the reliability of the classic while addressing the ergonomic and durability requirements of modern professional use.</p><p><strong>Enhanced Ergonomics.</strong> The redesigned carry handle and improved weight distribution reduce operator fatigue during extended morning fogging operations. For municipal teams running 4–6 hour fogging drives, reduced fatigue directly improves operational safety and coverage consistency.</p><p><strong>Updated Chemical Circuit.</strong> Redesigned chemical flow path with improved valve geometry delivers more consistent output control. Operators report more precise chemical application and easier flow adjustment during operations.</p><p><strong>Reinforced Frame.</strong> Updated frame construction with improved joint specifications provides greater resistance to the mechanical stress of daily loading, transport, and field deployment — extending service life compared to the classic edition.</p>",
    features: [
      "Updated ergonomic carry handle and weight distribution",
      "Improved chemical circuit with enhanced valve geometry",
      "Reinforced frame construction for extended service life",
      "Same reliable pulse-jet resonance core as classic edition",
      "DC 12V auto-start: electronic ignition",
      "Grade 316L stainless steel chemical contact surfaces",
      "Compatible with all WHO-approved thermal fogging chemicals",
      "GeM Registered: government procurement ready",
    ],
    specifications: [
      "Machine Type: Updated Pulse-Jet Thermal Fogger",
      "Edition: New Design (2024 Update)",
      "Start System: DC 12V Electric Auto-Start",
      "Power Source: Rechargeable 12V DC Battery",
      "Chemical Tank: Grade 316L Stainless Steel",
      "Spray Distance: Up to 6–8 metres",
      "Droplet Size: 8–15 microns (ultra-fine thermal fog)",
      "Key Improvement: Enhanced ergonomics + reinforced frame",
      "Operation Mode: Continuous duty",
      "Origin: India (updated design)",
      "Certifications: ISO 9001:2015, GeM Registered, MSME/UDYAM",
    ],
    applications: [
      "Municipal mosquito control (dengue, malaria, chikungunya)",
      "Professional pest control company operations",
      "Agricultural crop and plantation pest management",
      "Hospital and facility fumigation",
      "Government health department vector control",
      "Poultry and livestock farm disinfection",
      "Residential colony fogging",
      "Industrial zone pest control",
    ],
    certifications: CERTS,
    ...WARRANTY,
    productFaqs: FOGGING_FAQS,
    filmChapters: [
      {
        title: "Same Core. Better Ergonomics.",
        subtitle: "Operator feedback built into every design decision",
        description: "The New Edition retains the proven pulse-jet resonance core that field operators worldwide have trusted for decades. The updates — redesigned handle, improved weight distribution, updated frame geometry — all came directly from feedback by professional field operators who run these machines 5 days a week.",
        imageUrl: `${V}/2000new.jpg`,
        videoUrl: "",
        sortOrder: 1,
      },
      {
        title: "Reinforced Frame — Built for Daily Professional Use",
        subtitle: "Updated joint specifications for longer service intervals",
        description: "The New Edition's reinforced frame addresses the most common maintenance point of the classic design. Improved joint and mounting specifications resist the daily mechanical stress of loading/unloading, transport in field vehicles, and outdoor operation across years of professional use — extending service intervals and reducing total maintenance cost.",
        imageUrl: `${V}/2000new.jpg`,
        videoUrl: "",
        sortOrder: 2,
      },
    ],
    ugcImages: [],
    whatsappMessageText: "Hi 100X Circle, I'm interested in the Minisuper 2000 Gold New Edition. Please share pricing and availability.",
    h1Title: "Minisuper 2000 Gold New Edition — Updated Korean Pulse-Jet Thermal Fogger",
  },
];

// ─── SPARE PARTS ──────────────────────────────────────────────────────────────

const COMPAT = ["Thermal & Cold Fogging Machine-100XTFS50", "Thermal & cold fogging machine 100XTFS50", "100X ULV Cold Fogger BF-105", "100X ULV Cold Fogger BF-115", "100X Thermal Fogger BF-150", "100X Thermal Fogger BF-200", "100X Heavy-Duty Thermal Fogger BF-400", "100X Minisuper 2000 Gold — Classic Edition", "100X Minisuper 2000 Gold — New Edition"];
const COMPAT_150_200 = ["Thermal & Cold Fogging Machine-100XTFS50", "Thermal & cold fogging machine 100XTFS50", "Thermal Fogging Machine with Stainless steel tank -100XSSMA20", "ISI marked Thermal Fogging Machine with HDPE tank-100XHM20", "Small mini fogger -100XKB200", "Cold fogger machine with 2 stoke engine- 100XMCF42", "100X Thermal Fogger BF-150", "100X Thermal Fogger BF-200", "100X Heavy-Duty Thermal Fogger BF-400", "100X Minisuper 2000 Gold — Classic Edition", "100X Minisuper 2000 Gold — New Edition"];

const SPARE_PARTS = [
  // ── TANK & FLUID SYSTEMS ─────────────────────────────────────────────────
  {
    name: "Chemical Tank — 8L Stainless Steel SS316L",
    sku: "100X-SP-TANK-CHEM-8L",
    category: "Tank & Fluid Systems",
    description: "Complete 8-litre Grade 316L marine stainless steel chemical tank for BF-150 and BF-200 series foggers. Includes all mounting fittings. Replaces corroded or damaged tanks.",
    images: [`${V}/ถังน้ำยาอะไหล่เบสBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Tank — 1.8L with Fittings",
    sku: "100X-SP-TANK-FUEL-18",
    category: "Tank & Fluid Systems",
    description: "Complete 1.8-litre fuel tank assembly with mounting brackets for BF-150/200 series pulse-jet thermal foggers. Includes fuel pickup and vent fittings.",
    images: [`${V}/ถังน้ำมัน-อะไหล่BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Chemical Tank Connector — 3-Way Fitting",
    sku: "100X-SP-CONN-CHEM-3WAY",
    category: "Tank & Fluid Systems",
    description: "Three-way chemical tank connector fitting. Connects chemical tank to pump and lance assembly. Replace when fitting shows cracking, chemical seepage, or loose connection.",
    images: [`${V}/ข้อต่อถังน้ำยาอะไหล่BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Chemical Tank Cap with Seal",
    sku: "100X-SP-CAP-CHEM",
    category: "Tank & Fluid Systems",
    description: "Chemical tank filler cap with integrated rubber seal ring. Replace when cap shows seal degradation, chemical odour leakage, or pressure loss during operation.",
    images: [`${V}/ฝาปิดถังน้ำยาลูกยางกันกลับBF150.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Tank Cap with O-Ring",
    sku: "100X-SP-CAP-FUEL",
    category: "Tank & Fluid Systems",
    description: "Fuel tank filler cap with O-ring seal for BF-150/200 foggers. Replace when fuel odour escapes during operation or cap becomes difficult to seal.",
    images: [`${V}/ฝาปิดถังน้ำมัน.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Cap O-Ring Gasket",
    sku: "100X-SP-ORING-FUEL-CAP",
    category: "Tank & Fluid Systems",
    description: "Replacement O-ring gasket for fuel tank cap. Required replacement part when fuel seepage detected around tank cap. Low-cost preventive maintenance item.",
    images: [`${V}/ปะเก็นฝาถังBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Filter Element",
    sku: "100X-SP-FILTER-FUEL",
    category: "Tank & Fluid Systems",
    description: "Inline fuel filter for BF-150/200 foggers. Prevents fuel impurities from entering the carburetor. Recommended replacement every 50 hours of operation or annually.",
    images: [`${V}/ไส้กรองน้ำมันBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── VALVES & FLOW CONTROL ────────────────────────────────────────────────
  {
    name: "Chemical On/Off Valve Assembly",
    sku: "100X-SP-VALVE-CHEM-ONOFF",
    category: "Valves & Flow Control",
    description: "Chemical flow on/off valve for BF-150/200 foggers. Controls chemical feed to the nozzle. Replace when valve sticks, leaks, or fails to fully shut off chemical flow.",
    images: [`${V}/วาล์วปิดเปิดน้ำยาBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Chemical Flow Adjustment Valve",
    sku: "100X-SP-VALVE-CHEM-ADJ",
    category: "Valves & Flow Control",
    description: "Chemical output flow rate adjustment valve. Controls application rate from minimum to maximum. Replace when fine adjustment is no longer possible or valve becomes stuck.",
    images: [`${V}/วาล์วปรับน้ำยาเคมีBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Check Valve (Anti-Return Rubber Ball)",
    sku: "100X-SP-VALVE-CHECK-FUEL",
    category: "Valves & Flow Control",
    description: "Fuel circuit check valve preventing backflow. Critical for maintaining correct fuel pressure in the carburetor circuit. Replace when engine starts hard or fuel flow is inconsistent.",
    images: [`${V}/ลูกยางกันกลับน้ำมันBF150.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Chemical Check Valve (Anti-Return Rubber Ball)",
    sku: "100X-SP-VALVE-CHECK-CHEM",
    category: "Valves & Flow Control",
    description: "Chemical circuit check valve preventing chemical backflow into pump assembly. Replace when chemical drips from nozzle after valve is closed or flow is irregular.",
    images: [`${V}/ลูกยางกันกลับน้ำยาลูกยางกันกลับBF150.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Tank Check Valve",
    sku: "100X-SP-VALVE-CHECK-FTANK",
    category: "Valves & Flow Control",
    description: "Fuel tank anti-return check valve preventing fuel backflow. Essential for maintaining fuel circuit pressure. Replace when fuel consumption increases abnormally or engine operation is erratic.",
    images: [`${V}/วาล์วกันกลับBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Chemical Tank Check Valve",
    sku: "100X-SP-VALVE-CHECK-CTANK",
    category: "Valves & Flow Control",
    description: "Chemical tank anti-return check valve. Maintains chemical circuit pressure integrity. Replace when chemical output is irregular or pressure in chemical tank is lost.",
    images: [`${V}/วาล์วกันกลับถังน้ำยาBF150.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel Oil Valve (Inline Shutoff)",
    sku: "100X-SP-VALVE-FUEL-SHUTOFF",
    category: "Valves & Flow Control",
    description: "Inline fuel shutoff valve for fuel feed line. Essential safety component to cut fuel supply when machine is not in use. Replace when valve does not fully seal or becomes stiff.",
    images: [`${V}/วาล์วน้ำมันเชื้อเพลิง.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "3-Way Fuel Tank Connector",
    sku: "100X-SP-CONN-FUEL-3WAY",
    category: "Tank & Fluid Systems",
    description: "Three-way connector fitting for fuel tank circuit. Connects fuel tank, filter, and carburetor feed lines. Replace when fitting cracks, fuel seeps, or connections become loose.",
    images: [`${V}/ข้อต่อสามทางBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Nozzle Connector / Head Fitting",
    sku: "100X-SP-CONN-NOZZLE",
    category: "Output & Nozzle",
    description: "Nozzle head connector fitting. Connects chemical feed to the fog discharge nozzle. Replace when nozzle threads are damaged, chemical drips from connector joint, or fog pattern is irregular.",
    images: [`${V}/ข้อต่อหัวฉีดเฟรมบBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fog Nozzle / Spray Head",
    sku: "100X-SP-NOZZLE-HEAD",
    category: "Output & Nozzle",
    description: "Replacement fog discharge nozzle for BF-150/200 series. The precision-engineered nozzle geometry is critical to correct droplet size and spray pattern. Replace when fog pattern becomes uneven, spray distance reduces, or nozzle is physically damaged.",
    images: [`${V}/หัวฉีดน้ำมันBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── CARBURETOR & ENGINE ──────────────────────────────────────────────────
  {
    name: "Upper Carburetor Assembly",
    sku: "100X-SP-CARB-UPPER",
    category: "Carburetor & Engine",
    description: "Upper carburetor body assembly for BF-150/200 pulse-jet foggers. The upper carburetor manages air-fuel mixture for combustion. Replace when engine fails to start, runs rough, or output is inconsistent after cleaning.",
    images: [`${V}/คาร์บูเรเตอร์ตัวบน.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Lower Carburetor Assembly",
    sku: "100X-SP-CARB-LOWER",
    category: "Carburetor & Engine",
    description: "Lower carburetor body assembly. Works with upper carburetor to manage fuel metering for combustion. Replace when fuel metering is erratic, engine floods, or performance degrades after cleaning.",
    images: [`${V}/คาร์บูเรเตอร์ตัวล่าง.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Air Intake Connector",
    sku: "100X-SP-CARB-CONN-AIR",
    category: "Carburetor & Engine",
    description: "Air intake connector fitting for carburetor. Delivers clean air to the carburetor intake. Replace when air intake seals are cracked, air leakage is detected, or connector is physically damaged.",
    images: [`${V}/ข้อต่อฉากคาร์บูเรเตอร์BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Intake Plate",
    sku: "100X-SP-CARB-PLATE",
    category: "Carburetor & Engine",
    description: "Carburetor air intake plate assembly. Regulates air flow into the carburetor. Replace when plate is warped, cracked, or intake air flow is restricted.",
    images: [`${V}/แผ่นเพลทข้อต่อฉากคาร์บูเรเตอร์BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Plate / Venturi Plate",
    sku: "100X-SP-CARB-VENTURI",
    category: "Carburetor & Engine",
    description: "Carburetor venturi/throat plate. Critical for maintaining correct air-fuel ratio in the combustion circuit. Replace when air-fuel ratio is incorrect or carburetor cannot be tuned correctly.",
    images: [`${V}/แผ่นเพลทคาร์บูเรเตอร์.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Diaphragm",
    sku: "100X-SP-CARB-DIAPHRAGM",
    category: "Carburetor & Engine",
    description: "Flexible rubber diaphragm for carburetor fuel metering system. The diaphragm is a wear item requiring periodic replacement. Replace when engine starts hard, runs lean, or fuel metering becomes unreliable.",
    images: [`${V}/แผ่นไดอะเฟรมBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Gasket Set",
    sku: "100X-SP-CARB-GASKET",
    category: "Carburetor & Engine",
    description: "Complete carburetor gasket set for BF-150/200 foggers. Includes all sealing gaskets for upper and lower carburetor body. Replace during full carburetor rebuild or when fuel seepage is detected.",
    images: [`${V}/ปะเก็นคาบูเรเตอร์BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Upper Carburetor Funnel",
    sku: "100X-SP-CARB-FUNNEL-UPPER",
    category: "Carburetor & Engine",
    description: "Upper carburetor fuel funnel/bowl. Maintains fuel reservoir for carburetor operation. Replace when funnel is cracked, warped, or fuel metering is unreliable.",
    images: [`${V}/กรวยคาร์บูเรเตอร์ตัวบน.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Lower Carburetor Funnel",
    sku: "100X-SP-CARB-FUNNEL-LOWER",
    category: "Carburetor & Engine",
    description: "Lower carburetor fuel funnel/bowl. Works with upper funnel in the twin-stage fuel metering system. Replace when lower carburetor metering is unreliable or fuel seeps past the lower body.",
    images: [`${V}/กรวยคาร์บูเรเตอร์BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Centre Bolt (Upper)",
    sku: "100X-SP-BOLT-CARB-UPPER",
    category: "Carburetor & Engine",
    description: "Short upper carburetor mounting bolt. Secures upper carburetor body. Replace when thread is stripped or bolt is corroded.",
    images: [`${V}/น๊อตคาร์บูเรเตอร์-บน-สั้นBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Centre Bolt (Lower Chamber)",
    sku: "100X-SP-BOLT-CARB-LOWER",
    category: "Carburetor & Engine",
    description: "Lower carburetor chamber centre bolt. Secures lower carburetor assembly. Replace when stripped, corroded, or carburetor body alignment is compromised.",
    images: [`${V}/น๊อตกลางห้องคาร์บูBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Carburetor Rear Closure Bolt",
    sku: "100X-SP-BOLT-CARB-REAR",
    category: "Carburetor & Engine",
    description: "Rear carburetor closure bolt. Seals rear of carburetor body assembly. Replace when fuel seepage is detected at carburetor rear or bolt thread is stripped.",
    images: [`${V}/น๊อตปิดท้ายคาร์บูเรเตอร์.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Spark Plug",
    sku: "100X-SP-SPARK-PLUG",
    category: "Carburetor & Engine",
    description: "Replacement spark plug for BF-150/200 pulse-jet fogger ignition system. Replace when engine fails to start, ignition is intermittent, or electrode shows wear. Standard scheduled maintenance item every 100 hours.",
    images: [`${V}/หัวเทียน.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── ELECTRICAL & IGNITION ────────────────────────────────────────────────
  {
    name: "12V Rechargeable Battery — Genuine OEM",
    sku: "100X-SP-BATT-12V-OEM",
    category: "Electrical & Ignition",
    description: "Genuine OEM 12V rechargeable battery for BF-150/200 auto-start ignition system. Battery powers the electronic ignition circuit only (not continuous operation). Replace when machine requires multiple start attempts or battery holds charge for fewer than 50 starts.",
    images: [`${V}/แบตเตอรี่เท่าBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "12V Compatible Replacement Battery",
    sku: "100X-SP-BATT-12V-COMPAT",
    category: "Electrical & Ignition",
    description: "High-quality compatible replacement 12V battery for BF-150/200 auto-start system. Equivalent specification to OEM battery. Cost-effective alternative for fleet operators managing multiple machines.",
    images: [`${V}/แบตเตอรี่เทียบเท่าBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Ignition Coil Assembly",
    sku: "100X-SP-COIL-IGNIT",
    category: "Electrical & Ignition",
    description: "Electronic ignition coil assembly for BF-150/200 foggers. Generates the high-voltage spark for auto-start ignition sequence. Replace when engine fails to start despite charged battery and good spark plug.",
    images: [`${V}/คอล์ยไฟBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Start Button Switch Assembly",
    sku: "100X-SP-SWITCH-START",
    category: "Electrical & Ignition",
    description: "Auto-start button switch assembly for BF-150/200 foggers. The momentary contact button activates the ignition sequence. Replace when button sticks, fails to make contact, or machine requires multiple button presses to start.",
    images: [`${V}/สวิสสตาร์ทBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Battery Charging Jack",
    sku: "100X-SP-JACK-CHARGE",
    category: "Electrical & Ignition",
    description: "Battery charging input jack connector for BF-150/200 foggers. Receives the battery charger plug for post-use recharging. Replace when charging connection is intermittent or connector is physically damaged.",
    images: [`${V}/แจ็คชาร์จแบตแบตเตอรี่BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Battery Charger Adapter — Original Version",
    sku: "100X-SP-CHGR-ORIG",
    category: "Electrical & Ignition",
    description: "Original-version battery charger adapter for BF-150/200 foggers. Supplies correct charging voltage and current to the 12V battery. Replace when charging is slow, fails, or charger is physically damaged.",
    images: [`${V}/อะแดปเตอร์ชาร์จตัวเดิม.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Battery Charger Adapter — New Version",
    sku: "100X-SP-CHGR-NEW",
    category: "Electrical & Ignition",
    description: "Updated-version battery charger adapter for BF-150/200 foggers (2024 model). Improved charging circuit for faster and more reliable battery recharge. Compatible with both original and updated battery specifications.",
    images: [`${V}/อะแดปเตอร์ชาร์จตัวใหม่.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Battery Positive Wire Assembly",
    sku: "100X-SP-WIRE-BATT-POS",
    category: "Electrical & Ignition",
    description: "Battery positive lead wire with connector for BF-150/200 ignition system. Replace when wire insulation is cracked, connection is corroded, or intermittent electrical faults occur.",
    images: [`${V}/สายไฟขั้วบวก.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Battery Negative Wire Assembly",
    sku: "100X-SP-WIRE-BATT-NEG",
    category: "Electrical & Ignition",
    description: "Battery negative (ground) lead wire with connector for BF-150/200 ignition system. Replace when wire shows insulation damage, corrosion, or intermittent electrical grounding issues.",
    images: [`${V}/สายไฟขั้วลบ.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Air Pump Positive Wire",
    sku: "100X-SP-WIRE-PUMP-POS",
    category: "Electrical & Ignition",
    description: "Positive power supply wire for the air pump motor in BF-150/200 foggers. Replace when air pump operates intermittently or fails to start despite battery being charged.",
    images: [`${V}/สายไฟเข้าปั๊มลมBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── PUMPS ────────────────────────────────────────────────────────────────
  {
    name: "Air Pump Assembly — Genuine OEM",
    sku: "100X-SP-PUMP-AIR-OEM",
    category: "Pumps",
    description: "Genuine OEM air pump assembly for BF-150/200 foggers. The air pump pressurises the chemical circuit and provides combustion air supply. Replace when chemical output pressure drops, machine operates with reduced fog output, or pump makes abnormal noise.",
    images: [`${V}/ปั๊มลมBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Air Pump Assembly — Compatible Replacement",
    sku: "100X-SP-PUMP-AIR-COMPAT",
    category: "Pumps",
    description: "High-quality compatible replacement air pump for BF-150/200 foggers. Equivalent flow rate and pressure specification to OEM pump. Cost-effective option for fleet operators.",
    images: [`${V}/ปั๊มลมเทียบเท่า1BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── HOSES & TUBING ───────────────────────────────────────────────────────
  {
    name: "Air Hose Assembly",
    sku: "100X-SP-HOSE-AIR",
    category: "Hoses & Tubing",
    description: "Air pump output hose for BF-150/200 foggers. Connects air pump to carburetor and chemical feed circuit. Replace when hose shows cracking, hardening with age, or air pressure loss is detected.",
    images: [`${V}/สายลมBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Fuel/Oil Hose Assembly",
    sku: "100X-SP-HOSE-OIL",
    category: "Hoses & Tubing",
    description: "Fuel feed hose connecting fuel tank to carburetor for BF-150/200 foggers. Replace when hose shows cracking, fuel seepage, or fuel flow restriction (which causes engine running issues).",
    images: [`${V}/สายน้ำมันBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Air Pump Rubber Hose",
    sku: "100X-SP-HOSE-PUMP-RUBBER",
    category: "Hoses & Tubing",
    description: "Flexible rubber hose connecting air pump to the main air circuit. Provides vibration isolation and flexible routing for the air supply line. Replace when hose hardens, cracks, or air pressure loss is measured.",
    images: [`${V}/สายยางปั๊มลมBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Internal Tube BF-150 (Type 150-1)",
    sku: "100X-SP-TUBE-150-1",
    category: "Hoses & Tubing",
    description: "Internal resonance chamber tube for BF-150 series foggers. Critical component of the pulse-jet combustion path. Replace when combustion efficiency drops, machine requires excessive fuel, or tube shows corrosion damage.",
    images: [`${V}/61.jpg`],
    compatibleProductNames: ["Thermal & Cold Fogging Machine-100XTFS50", "Thermal & cold fogging machine 100XTFS50", "Small mini fogger -100XKB200", "100X Minisuper 2000 Gold — Classic Edition"],
  },
  {
    name: "Internal Tube BF-200 (Type 200-1)",
    sku: "100X-SP-TUBE-200-1",
    category: "Hoses & Tubing",
    description: "Internal resonance chamber tube for BF-200 series foggers. Higher output version of the internal tube. Replace when combustion efficiency drops or tube shows corrosion or heat damage.",
    images: [`${V}/62.jpg`],
    compatibleProductNames: ["Thermal Fogging Machine with Stainless steel tank -100XSSMA20", "ISI marked Thermal Fogging Machine with HDPE tank-100XHM20", "Cold fogger machine with 2 stoke engine- 100XMCF42", "100X Heavy-Duty Thermal Fogger BF-400", "100X Minisuper 2000 Gold — New Edition"],
  },

  // ── BODY, FRAME & HEAT MANAGEMENT ───────────────────────────────────────
  {
    name: "Machine Frame Assembly",
    sku: "100X-SP-FRAME",
    category: "Body & Frame",
    description: "Complete machine frame / body shell assembly for BF-150/200 foggers. Structural frame supporting all component mounting. Replace when frame is cracked, bent, or mounting points are damaged beyond repair.",
    images: [`${V}/เฟรมเครื่องลูกยางกันกลับBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Heat Shield Screen BF-150 (Inner Guard)",
    sku: "100X-SP-SHIELD-INNER-150",
    category: "Body & Frame",
    description: "Inner heat shield screen guard for BF-150 fogger. Protects operator and surroundings from the resonance chamber heat. Replace when guard is warped, perforated, or structurally compromised from heat stress.",
    images: [`${V}/ตะแกรงกันความร้อนBF150.jpg`],
    compatibleProductNames: ["Thermal & Cold Fogging Machine-100XTFS50", "Thermal & cold fogging machine 100XTFS50", "Small mini fogger -100XKB200", "100X Minisuper 2000 Gold — Classic Edition"],
  },
  {
    name: "Heat Shield Screen BF-200 (Inner Guard)",
    sku: "100X-SP-SHIELD-INNER-200",
    category: "Body & Frame",
    description: "Inner heat shield screen guard for BF-200 fogger. Compatible with higher-output BF-200 series thermal specifications. Replace when guard is warped from heat stress or structurally damaged.",
    images: [`${V}/ตะแกรงกันความร้อนBF150-BF200.jpg`],
    compatibleProductNames: ["Thermal Fogging Machine with Stainless steel tank -100XSSMA20", "ISI marked Thermal Fogging Machine with HDPE tank-100XHM20", "100X Heavy-Duty Thermal Fogger BF-400"],
  },
  {
    name: "External Heat Shield / Outer Guard",
    sku: "100X-SP-SHIELD-OUTER",
    category: "Body & Frame",
    description: "Outer heat shield guard providing external thermal protection during operation. Replace when outer guard is significantly dented, warped, or when heat-related marks appear on the machine exterior.",
    images: [`${V}/ตะแกรงกันความร้อนตัวนอก.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Internal Cooling Tube (Inner)",
    sku: "100X-SP-COOL-TUBE-INNER",
    category: "Body & Frame",
    description: "Internal cooling tube for heat dissipation from the combustion chamber. Maintains operating temperature within safe range for continuous-duty operation. Replace when machine overheats or cooling performance degrades.",
    images: [`${V}/ท่อระบายความร้อนตัวในBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "External Cooling Tube (Short, Outer)",
    sku: "100X-SP-COOL-TUBE-OUTER",
    category: "Body & Frame",
    description: "External short cooling tube for outer heat dissipation circuit. Complements the internal cooling tube for full cooling system performance. Replace when external cooling efficiency is reduced or tube shows heat damage.",
    images: [`${V}/ท่อระบายความร้อนตัวนอกสั้น.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Exhaust / Combustion Pipe",
    sku: "100X-SP-PIPE-EXHAUST",
    category: "Body & Frame",
    description: "Exhaust pipe for the pulse-jet combustion circuit. Directs combustion gases and contributes to the resonance cycle. Replace when pipe shows perforations, cracks, or combustion performance degrades.",
    images: [`${V}/ท่อเฝาไหม้แบตเตอรี่BF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Shoulder / Carry Strap",
    sku: "100X-SP-STRAP-CARRY",
    category: "Accessories",
    description: "Replacement shoulder carry strap for BF-150/200 foggers. Padded shoulder strap for comfortable single-operator field carrying. Replace when strap buckles fail, webbing frays, or strap loses padding support.",
    images: [`${V}/48.png`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── VALVES & FLOW CONTROL (BF-200 specific) ─────────────────────────────
  {
    name: "Fog Switch Valve — BF-200",
    sku: "100X-SP-VALVE-FOG-SWITCH-200",
    category: "Valves & Flow Control",
    description: "Fog diverter/switch valve specific to BF-200 thermal foggers. Controls fog output switching and chemical flow direction in the higher-output BF-200 circuit. Replace when fog output is inconsistent, valve sticks in one position, or chemical flow cannot be controlled.",
    images: [`${V}/วาล์วสับหมอกควันBF200.jpg`],
    compatibleProductNames: ["100X Thermal Fogger BF-200", "Thermal Fogging Machine with Stainless steel tank -100XSSMA20", "100X Heavy-Duty Thermal Fogger BF-400"],
  },

  // ── TANK & FLUID SYSTEMS (additional fittings) ──────────────────────────
  {
    name: "Fuel Tank Connector Fitting",
    sku: "100X-SP-CONN-FUEL-TANK",
    category: "Tank & Fluid Systems",
    description: "Fuel tank outlet connector fitting for BF-150/200 foggers. Connects the fuel tank to the main fuel feed line. Distinct from the 3-way splitter — this is the direct tank outlet fitting. Replace when fuel seepage is detected at the tank connection point or fitting thread is damaged.",
    images: [`${V}/ข้อต่อถังน้ำมันBF150-BF200.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── LANCE & NOZZLE ASSEMBLY ──────────────────────────────────────────────
  {
    name: "Chemical Spray Lance Assembly — Type A",
    sku: "100X-SP-LANCE-A",
    category: "Output & Nozzle",
    description: "Chemical spray lance assembly for BF-150/200 thermal foggers — Type A variant. The lance directs the thermal fog from the combustion chamber to the discharge nozzle. Replace when lance shows corrosion, bending damage, or chemical flow is restricted.",
    images: [`${V}/57.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Resonance Chamber Tube — Section 3",
    sku: "100X-SP-TUBE-SEC3",
    category: "Carburetor & Engine",
    description: "Third-section resonance chamber tube for pulse-jet combustion circuit. Part of the tuned resonance pipe assembly that drives the pulse-jet combustion cycle. Replace when combustion efficiency drops, machine runs rough, or tube shows heat stress damage.",
    images: [`${V}/63.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Resonance Chamber Tube — Section 4",
    sku: "100X-SP-TUBE-SEC4",
    category: "Carburetor & Engine",
    description: "Fourth-section resonance chamber tube. Part of the tuned exhaust resonance circuit. Replace when combustion resonance is disrupted, output drops, or tube shows corrosion from extended high-temperature operation.",
    images: [`${V}/64.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Combustion Chamber Extension Pipe",
    sku: "100X-SP-PIPE-CHAMBER-EXT",
    category: "Carburetor & Engine",
    description: "Combustion chamber extension pipe for the pulse-jet resonance assembly. Extends the tuned resonance length for correct pulse-jet operation. Replace when combustion is erratic, output is weak, or pipe shows stress fractures from heat cycling.",
    images: [`${V}/65.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Lance Mounting Bracket Assembly",
    sku: "100X-SP-BRACKET-LANCE",
    category: "Body & Frame",
    description: "Mounting bracket assembly for chemical lance on BF-150/200 foggers. Secures the lance to the machine frame and maintains correct lance alignment for optimal fog discharge. Replace when bracket is bent, cracked, or lance is misaligned during operation.",
    images: [`${V}/66.png`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Air Intake Silencer / Muffler",
    sku: "100X-SP-SILENCER-AIR",
    category: "Carburetor & Engine",
    description: "Air intake silencer/muffler for BF-150/200 foggers. Reduces intake noise during combustion cycle and conditions air flow into the carburetor. Replace when machine noise increases noticeably or intake flow restriction is detected.",
    images: [`${V}/67.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },
  {
    name: "Chemical Tank Drain / Outlet Plug",
    sku: "100X-SP-PLUG-DRAIN",
    category: "Tank & Fluid Systems",
    description: "Chemical tank drain plug for BF-150/200 foggers. Allows complete chemical drain after use for storage and cleaning. Replace when plug threads are stripped, chemical leaks around the drain point, or plug is physically damaged.",
    images: [`${V}/68.jpg`],
    compatibleProductNames: COMPAT_150_200,
  },

  // ── EXPLODED DIAGRAM (reference part) ───────────────────────────────────
  {
    name: "BF-150/200 Exploded Parts Diagram",
    sku: "100X-SP-DIAGRAM-150-200",
    category: "Technical Documentation",
    description: "Official exploded parts diagram for BF-150 and BF-200 thermal foggers. Shows all numbered components with their assembly positions. Essential reference for field technicians during maintenance and repair. All part numbers correspond to 100X Circle spare parts catalogue.",
    images: ["https://www.bestfoggerthailand.com/wp-content/uploads/2025/05/%E0%B8%AD%E0%B8%B0%E0%B9%84%E0%B8%AB%E0%B8%A5%E0%B9%88%E0%B9%80%E0%B8%9A%E0%B8%AA%E0%B8%9F%E0%B9%8A%E0%B8%AD%E0%B8%81%E0%B9%80%E0%B8%81%E0%B8%AD%E0%B8%A3%E0%B9%8C-1024x652-1.png"],
    compatibleProductNames: COMPAT_150_200,
    priceRange: "Free — included with purchase",
  },
];

// ─── Main handler ─────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));
    if (body.token !== TOKEN) {
      return NextResponse.json({ error: "Invalid token" }, { status: 401 });
    }

    const client = await clientPromise;
    const db = client.db();
    const now = new Date().toISOString();

    const results = { products: [] as string[], spare_parts: [] as string[], skipped: [] as string[] };

    // ── Create new products (skip if slug already exists) ─────────────────
    for (const p of NEW_PRODUCTS) {
      const existing = await db.collection("products").findOne({ slug: p.slug });
      if (existing) {
        results.skipped.push(`product:${p.slug}`);
        continue;
      }
      const doc = {
        ...p,
        createdAt: now,
        updatedAt: now,
        order: 100,
      };
      await db.collection("products").insertOne(doc);
      results.products.push(p.name);
    }

    // ── Create spare parts (skip if SKU already exists) ───────────────────
    for (const sp of SPARE_PARTS) {
      const existing = await db.collection("spare_parts").findOne({ sku: sp.sku });
      if (existing) {
        results.skipped.push(`part:${sp.sku}`);
        continue;
      }
      const slugStr = sp.name.toLowerCase().replace(/[^a-z0-9\s-]/g, "").trim().replace(/\s+/g, "-");
      const doc = {
        ...sp,
        slug: slugStr,
        priceRange: (sp as any).priceRange || "Price on Request",
        isPublished: true,
        order: 0,
        createdAt: now,
        updatedAt: now,
      };
      await db.collection("spare_parts").insertOne(doc);
      results.spare_parts.push(sp.name);
    }

    return NextResponse.json({
      success: true,
      created: {
        products: results.products.length,
        spare_parts: results.spare_parts.length,
      },
      skipped: results.skipped.length,
      detail: results,
    });

  } catch (err) {
    console.error("seed-complete error:", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    info: "POST with { token: '100x_complete_2026' } to create all products + spare parts.",
    creates: `${NEW_PRODUCTS.length} products + ${SPARE_PARTS.length} spare parts`,
  });
}
